require "minitest/autorun"
require "minitest/rg"
require "sinatra/activerecord"
require_relative "../app/models/book.rb"
require_relative "../app/models/patron.rb"
require_relative "../app/models/library.rb"
require_relative "../app/models/staff_member.rb"
