development:
  host: 'localhost'
  adapter: 'postgresql'
  database: 'week-five-project'
  encoding: 'utf8'
  pool: 5
  username: patrick
  password: patrick
test:
  host: 'localhost'
  adapter: 'postgresql'
  database: 'week-five-project-test'
  encoding: 'utf8'
  pool: 5
  username: patrick
  password: patrick
