# Put your seed data in here. This should be a series of .create! statements for
# each of your relevant models.
#
# You'll run it with rake db:seed

Club.create(name: "Liverpool", city: "Liverpool")
Club.create(name: "Everton", city: "Liverpool")
Club.create(name: "Leicester City", city: "Leicester")
Club.create(name: "Tottenham Hotspur", city: "London")
Club.create(name: "Manchester United", city: "Manchester")
Club.create(name: "Manchester City", city: "Manchester")
Club.create(name: "Arsenal", city: "London")
Club.create(name: "Chelsea", city: "London")
Club.create(name: "West Ham United", city: "London")
Club.create(name: "Watford", city: "London")

Sponsor.create(name: "Aviva", value: "£3.9M")
Sponsor.create(name: "Carlsberg", value: "£19.2M")
Sponsor.create(name: "King Power", value: "£7.9M")
Sponsor.create(name: "AIA", value: "£11.5M")
Sponsor.create(name: "Etihad", value: "£22.1M")
Sponsor.create(name: "Emirates", value: "£25.0M")
Sponsor.create(name: "Cheverolet", value: "£27.5M")
Sponsor.create(name: "Umbro", value: "£6.4M")
Sponsor.create(name: "Veho", value: "£9.7M")
Sponsor.create(name: "New Balance", value: "£5.9M")
Sponsor.create(name: "Yokohama", value: "£4.9M")

Player.create(name: "Mignolet", value: "£4.9M")
Player.create(name: "Bogdan", value: "£4.3M")
Player.create(name: "Ward", value: "£4.0M")
Player.create(name: "Clyne", value: "£5.2M")
Player.create(name: "Moreno", value: "£4.6M")
Player.create(name: "Lovren", value: "£4.8M")
Player.create(name: "Skrtel", value: "£5.3M")
Player.create(name: "Sakho", value: "£4.7M")
Player.create(name: "Touré", value: "£4.4M")
Player.create(name: "Gomez", value: "£4.2M")
Player.create(name: "Caulker", value: "£5.2M")
Player.create(name: "Flanagan", value: "£4.4M")
Player.create(name: "Firmino", value: "£8.1M")
Player.create(name: "Coutinho", value: "£8.3M")
Player.create(name: "Milner", value: "£6.5M")
Player.create(name: "Lallana", value: "£7.3M")
Player.create(name: "Can", value: "£5.3M")
Player.create(name: "Henderson", value: "£6.5M")
Player.create(name: "Ibe", value: "£4.4M")
Player.create(name: "Lucas", value: "£4.3M")
