# Put your seed data in here. This should be a series of .create! statements for
# each of your relevant models.
#
# You'll run it with rake db:seed

Club.create(name: "Liverpool", city: "Liverpool")
Club.create(name: "Everton", city: "Liverpool")
Club.create(name: "Leicester City", city: "Leicester")
Club.create(name: "Tottenham Hotspur", city: "London")
Club.create(name: "Manchester United", city: "Manchester")
Club.create(name: "Manchester City", city: "Manchester")
Club.create(name: "Arsenal", city: "London")
Club.create(name: "Chelsea", city: "London")
Club.create(name: "West Ham United", city: "London")
Club.create(name: "Watford", city: "London")
Club.create(name: "Sunderland", city: "Sunderalnd")
Club.create(name: "Aston Villa", city: "Birmingham")
Club.create(name: "Newcastle United", city: "Newcastle")
Club.create(name: "West Bromwich Albion", city: "West Bromwich")
Club.create(name: "Southampton", city: "Southampton")
Club.create(name: "Stoke City", city: "Stoke")
Club.create(name: "Bournemouth", city: "Bournemouth")
Club.create(name: "Swansea City", city: "Swansea")
Club.create(name: "Crystal Palace", city: "London")
Club.create(name: "Norwich City", city: "Norwich")


Sponsor.create(name: "Aviva", value: "£3.9M")
Sponsor.create(name: "Carlsberg", value: "£19.2M")
Sponsor.create(name: "King Power", value: "£7.9M")
Sponsor.create(name: "AIA", value: "£11.5M")
Sponsor.create(name: "Etihad", value: "£22.1M")
Sponsor.create(name: "Emirates", value: "£25.0M")
Sponsor.create(name: "Cheverolet", value: "£27.5M")
Sponsor.create(name: "Umbro", value: "£6.4M")
Sponsor.create(name: "Veho", value: "£9.7M")
Sponsor.create(name: "New Balance", value: "£5.9M")
Sponsor.create(name: "Yokohama", value: "£4.9M")
Sponsor.create(name: "Chang", value: "£8.1M")
Sponsor.create(name: "Puma", value: "£4.9M")
Sponsor.create(name: "Visit Britain", value: "£5.0M")
Sponsor.create(name: "Adidas", value: "£44.9M")
Sponsor.create(name: "Nike", value: "£50.0M")
Sponsor.create(name: "Macron", value: "£6.2M")
Sponsor.create(name: "Wonga", value: "£9.9M")
Sponsor.create(name: "QuickBooks", value: "£3.4M")
Sponsor.create(name: "Barclays", value: "£22.7M")

Player.create(name: "Mignolet", value: "£4.9M")
Player.create(name: "Bogdan", value: "£4.3M")
Player.create(name: "Ward", value: "£4.0M")
Player.create(name: "Clyne", value: "£5.2M")
Player.create(name: "Moreno", value: "£4.6M")
Player.create(name: "Lovren", value: "£4.8M")
Player.create(name: "Skrtel", value: "£5.3M")
Player.create(name: "Sakho", value: "£4.7M")
Player.create(name: "Touré", value: "£4.4M")
Player.create(name: "Gomez", value: "£4.2M")
Player.create(name: "Caulker", value: "£5.2M")
Player.create(name: "Flanagan", value: "£4.4M")
Player.create(name: "Stewart", value: "£4.5M")
Player.create(name: "Smith", value: "£4.0M")
Player.create(name: "Enrique", value: "£4.1M")
Player.create(name: "Ilori", value: "£4.4M")
Player.create(name: "Randall", value: "£4.0M")
Player.create(name: "Firmino", value: "£8.1M")
Player.create(name: "Coutinho", value: "£8.3M")
Player.create(name: "Milner", value: "£6.5M")
Player.create(name: "Lallana", value: "£7.3M")
Player.create(name: "Can", value: "£5.3M")
Player.create(name: "Henderson", value: "£6.5M")
Player.create(name: "Ibe", value: "£4.4M")
Player.create(name: "Lucas", value: "£4.3M")
Player.create(name: "Allen", value: "£4.9M")
Player.create(name: "Rossiter", value: "£4.4M")
Player.create(name: "Teixeira", value: "£4.5M")
Player.create(name: "Brannagan", value: "£4.5M")
